### ISSUE TITLE
Enhancement: Migration support for Docker Compose to Helm

### ISSUE THREAD

**Issue by malvidin** [CybercentreCanada/assemblyline-helm-chart#19]
It would be nice to have information on the following, since Docker Compose support is no longer provided.
1. Migration of data
2. Configuration files (e.g. classification.yaml)
3. How to develop AL Services using Helm instead of Docker

**Comment by cccs-rs** [comment]
Hello! These are definitely things we'll document before deprecating Docker Compose.

Some ideas off the top of my head:

1.  It may be possible to mount the original volumes from Docker in Kubernetes using a [hostpath](https://kubernetes.io/docs/concepts/storage/volumes/#hostpath) volume mount.
2. Configuration files can be added as ConfigMaps in Kubernetes and you can mount them using the coreMounts & coreVolume values in the values.yaml
3. I'm currently working on something for developing for AL in Kubernetes (both core and services): https://github.com/CybercentreCanada/assemblyline-base/pull/315

All of the above will be properly tested and documented to ease the transition from one appliance type to the other. Stay tuned!

**Comment by cccs-rs** [comment]
Documentation addressing points 1 & 2 have now been added to our official documentaition, see: [Appliance Migration - Assemblyline 4](https://cybercentrecanada.github.io/assemblyline4_docs/installation/deployment_migration/)

As for point 3, service development will remain the same in which you can test your service by using `run_service_once` in the service-base as described [here](https://cybercentrecanada.github.io/assemblyline4_docs/developer_manual/services/run_your_service/#standalone-mode) or by running the service container live in a dev Docker deployment.

Kubernetes-specific development (so far) is usually for core components as services should run the same in either deployment environment, but we will continue to look for ways to expand on the service development process!
